version: "3"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'

  nginx1:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./docker/server1/configurationNginx.conf:/etc/nginx/conf.d/default.conf

  nginx2:
    image: nginx:latest
    ports:
      - '8082:80'
    volumes:
      - ./docker/server1/configurationNginx.conf:/etc/nginx/conf.d/default.conf

  php1:
    build: ./docker/server2
    ports:
      - '80:80'
    volumes:
      - ./src:/var/www/html

  php2:
    build: ./docker/server2
    ports:
      - '82:80'
    volumes:
      - ./src2:/var/www/html